---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  A basic template to get used to how to write CloudFormation files

Resources:
  ListS3BucketsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          const { S3Client, ListBucketsCommand } = require("@aws-sdk/client-s3");
          const s3 = new S3Client({ region: "eu-west-1" }); // replace "us-east-1" with your AWS region

          exports.handler = async function(event) {
            const command = new ListBucketsCommand({});
            const response = await s3.send(command);
            return response.Buckets;
          };
      Runtime: nodejs20.x
      Handler: index.handler
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement: 
        - Effect: Allow
          Principal: 
            Service: 
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies: 
      - PolicyName: root
        PolicyDocument: 
          Version: '2012-10-17'
          Statement: 
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
      - PolicyName: s3Access
        PolicyDocument: 
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: 
            - s3:ListAllMyBuckets
            Resource: arn:aws:s3:::*