---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  A basic template to get used to how to write CloudFormation files

Resources:
  lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          const { S3Client, ListBucketsCommand } = require("@aws-sdk/client-s3");
          const s3 = new S3Client({ region: "eu-west-1" }); // replace "us-east-1" with your AWS region

          exports.handler = async function(event) {
            const command = new ListBucketsCommand({});
            const response = await s3.send(command);
            return response.Buckets;
          };
        

